
project_id = "gfawccsiklzqvzchmbis"

[api]
enabled = true
url = "https://gfawccsiklzqvzchmbis.supabase.co"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmYXdjY3Npa2x6cXZ6Y2htYmlzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODk2MjUwNiwiZXhwIjoyMDY0NTM4NTA2fQ.wjHHyK0dhQtPr6L0hO3GAMXfPMdsdUvGUwxiLGlc-J8"

[functions.admin-upload-document]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.direito-chat]
verify_jwt = false

[functions.gerar-peticao]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
