// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfawccsiklzqvzchmbis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmYXdjY3Npa2x6cXZ6Y2htYmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjI1MDYsImV4cCI6MjA2NDUzODUwNn0.HtvsAkPOhlu0qlf4nYWYHQuuaB1tH43R9X-ytZ9IPH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);